### ISSUE TITLE
compilation errors with vala 0.44.4

### ISSUE THREAD

**Issue by decathorpe** [elementary/files#972]
After upgrading vala from 0.44.3 to 0.44.4, these errors started to make the build fail:

```
dee-1.0.vapi:44.35-44.44: error: construct properties not supported for specified property type
		public Dee.Filter filter { get; construct; }
		                                ^^^^^^^^^^
dee-1.0.vapi:76.35-76.44: error: construct properties not supported for specified property type
		public Dee.ModelReader reader { construct; }
		                                ^^^^^^^^^^
```

and this warning:

```
../src/Utils/MimeActions.vala:151.21-151.31: warning: `null' incompatible with return type `GLib.List<GLib.AppInfo>'
                    return null;
                    ^^^^^^^^^^^
```

**Comment by jeremypw** [comment]
I do not think the Dee vapi errors are related to the Files code, which does not use this library.  I think the warning has been around a while.

**Comment by jeremypw** [comment]
Looks like the Dee error occurs because of the dependency on libunity, which in turn depends on libdee.  Perhaps file a bug here `https://bugs.launchpad.net/dee`?  The error seems to still be in the master source.

**Comment by decathorpe** [comment]
Yes, it's still in the master code.

Right ... I had not considered that this might be caused by another library (dee), since shared libraries aren't compiled at the same time, but in this case the VAPI files are parsed later ... :weary:

Maybe @ricotz has an idea why a vala update would cause this issue?

**Comment by ricotz** [comment]
See https://gitlab.gnome.org/GNOME/vala/issues/803
